
PRT_HEXA:
	PUSH	AF			; SAVE AF
	PUSH	BC
	PUSH	DE			; SAVE DE
	PUSH	HL
	CALL	HEXASCII		; CONVERT VALUE IN A TO HEX CHARS IN DE
	PUSH	HL
	LD	E, H			; GET THE HIGH ORDER HEX CHAR
	BDOSFN	CONOUT			; PRINT IT
	POP	DE
	BDOSFN	CONOUT			; PRINT IT
	LD	E, ' '
	BDOSFN	CONOUT
	POP	HL
	POP	DE			; RESTORE DE
	POP	BC
	POP	AF			; RESTORE AF
	RET				; DONE


;===============================================================================
; CONVERT BINARY VALUE IN A TO ASCII HEX CHARACTERS IN HL

HEXASCII:
	LD	H, A			; SAVE A IN D
	CALL	HEXCONV			; CONVERT LOW NIBBLE OF A TO HEX
	LD	L, A			; SAVE IT IN E
	LD	A, H			; GET ORIGINAL VALUE BACK
	RLCA				; ROTATE HIGH ORDER NIBBLE TO LOW BITS
	RLCA
	RLCA
	RLCA
	CALL	HEXCONV			; CONVERT NIBBLE
	LD	H, A			; SAVE IT IN D
	RET				; DONE

;===============================================================================
; CONVERT LOW NIBBLE OF A TO ASCII HEX

HEXCONV:
	AND	$0F	     		; LOW NIBBLE ONLY
	ADD	A, $90
	DAA
	ADC	A, $40
	DAA
	RET


PRT_BUFF_STATE:
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL

	BDOSFN	STROUT

	LD	DE, MSG.BUFFSTATE
	BDOSFN	STROUT

	LD	HL, SIO_RCVBUF
	LD	B, 5

LOOP:
	LD	A, (HL)
	CALL	PRT_HEXA
	INC	HL
	DJNZ	LOOP

	LD	DE, MSG.NEWLINE
	BDOSFN	STROUT

	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET

MSG.BUFFSTATE	DB	"buf: \r\n$"
