DRV_INIT_CH376:
	CALL	CH_RESET
	LD	BC, WAIT_ONE_SECOND/10
	CALL	WAIT

	CALL	CH_HW_TEST
	JR	NC, CH376_FOUND

CH376_NOT_FOUND:
	LD	HL, CH376_NOT_FOUND_MSG
	CALL	PRINT
	XOR	A
	RET

CH376_FOUND:
	; LD	HL, CH376_FOUND_MSG
	; CALL	PRINT

	CALL	INIWORK		; Initialize the work-area

	LD	A, (IX+WRKAREA.STATUS)
	SET	0, A
	LD	(IX+WRKAREA.STATUS), A

	; CHECK AND DISPLAY CH376S IC/FIRMWARE VERSION
	LD	HL, CH376_FOUND_MSG
	CALL	PRINT
	CALL	CH_IC_VERSION
	ADD	A, '0'
	CALL	CHPUT
	LD	HL, CH376_NEWLINE
	CALL	PRINT

	OR	255
	RET

; ------------------------------------------------
; Initialize the Work-area
; ------------------------------------------------
INIWORK:
	; CLEAR THE WORKAREA
	LD	HL, IX
	LD	DE, HL
	INC	DE
	LD	BC, WRKAREA-1 ; SIZE OF WRKAREA
	XOR	A
	LD	(HL),A
	LDIR

	; COPY NXT_DIRECT TO WORK-AREA
	JP	NXT_DIRECT_WRKAREA

CH376_NOT_FOUND_MSG:
	DB	"CH376:           NOT PRESENT", 13, 10, 0
CH376_FOUND_MSG
	DB	"CH376:           PRESENT (VER ", 0
CH376_NEWLINE:
	DB	")\r\n",0
