	PUBLIC	_scanRow, _initPPI

	SECTION code_user

PSL_STAT:       EQU     $A8             ; slot status
KBD_STAT:       EQU     $A9             ; keyboard status
GIO_REGS:       EQU     $AA             ; General IO Register
PPI_REGS:       EQU     $AB             ; PPI register

PPICMD_CLOW_IN		EQU	1
PPICMD_CLOW_OUT		EQU	0
PPICMD_B_IN		EQU	2
PPICMD_B_OUT		EQU	0
PPICMD_GB_MODE_0	EQU	0
PPICMD_GB_MODE_1	EQU	4
PPICMD_CHIGH_IN		EQU	8
PPICMD_CHIGH_OUT	EQU	0
PPICMD_A_IN		EQU	16
PPICMD_A_OUT		EQU	0
PPICMD_GA_MODE_0	EQU	0
PPICMD_GA_MODE_1	EQU	32
PPICMD_GA_MODE_2	EQU	64
PPICMD_COMMAND		EQU	128

_initPPI:
	; CONFIGURE 8255 PPI PORTS
	; A - INPUT (NOT USED)
	; B - INPUT (COLUMN LINES)
	; C - OUTPUT (ROW LINE SELECTION)

	LD	A, PPICMD_COMMAND | PPICMD_GA_MODE_0 | PPICMD_GB_MODE_0 | PPICMD_A_IN | PPICMD_B_IN | PPICMD_CLOW_OUT | PPICMD_CHIGH_OUT
	OUT	(PPI_REGS), A
	LD	A, 64			; CAPS OFF
	OUT	(GIO_REGS), A
	RET

_scanRow:
	IN	A, (GIO_REGS)
	AND	$F0
	ADD	L			; Add requested row 0 to 8

	OUT	(GIO_REGS), A
	IN	A, (KBD_STAT)
	LD	L, A

	RET
