name: yellow-msx

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  yellow-msx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: pull docker tool chain
        run: docker pull vipoo/yellow-msx-rc2014-tool-chain:0.0.13

      - name: build-jeds
        run: docker run --rm --privileged=true -v ./:/src/ -t vipoo/yellow-msx-rc2014-tool-chain:0.0.13 make RELEASE=true -C msx jeds

      - name: build-rc2014-apps
        run: docker run --rm --privileged=true -v ./:/src/ -t vipoo/yellow-msx-rc2014-tool-chain:0.0.13 make RELEASE=true -C apps-rc2014 -B

      - name: build-msx-apps
        run: docker run --rm --privileged=true -v ./:/src/ -t vipoo/yellow-msx-rc2014-tool-chain:0.0.13 make RELEASE=true -C msx/apps

      - name: build-msx-roms
        run: docker run --rm --privileged=true -v ./:/src/ -t vipoo/yellow-msx-rc2014-tool-chain:0.0.13 make RELEASE=true -C msx VERSION=$(date +%Y-%m-%d)

