name: yellow-msx

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  yellow-msx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: build
        run: docker run --rm --privileged=true -v ./:/src/ -t vipoo/yellow-msx-rc2014-tool-chain:latest make release-build
