name: yellow-msx

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  yellow-msx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: pull docker tool chain
        run: docker pull vipoo/yellow-msx-rc2014-tool-chain:0.0.21

      - name: clean
        run: docker run --rm --privileged=true -v ./:/src/ -t vipoo/yellow-msx-rc2014-tool-chain:0.0.21 make clean

      - name: release-notes
        run: docker run --rm --privileged=true -v ./:/src/ -t vipoo/yellow-msx-rc2014-tool-chain:0.0.21 make release-notes

      - name: build-jeds
        run: docker run --rm --privileged=true -v ./:/src/ -t vipoo/yellow-msx-rc2014-tool-chain:0.0.21 make release-build-jeds

      - name: build-msx-apps
        run: docker run --rm --privileged=true -v ./:/src/ -t vipoo/yellow-msx-rc2014-tool-chain:0.0.21 make release-build-msx-apps

      - name: build-msx-roms
        run: docker run --rm --privileged=true -v ./:/src/ -t vipoo/yellow-msx-rc2014-tool-chain:0.0.21 make release-build-msx-roms

      - name: build-rc2014-apps
        run: docker run --rm --privileged=true -v ./:/src/ -t vipoo/yellow-msx-rc2014-tool-chain:0.0.21 make release-build-rc2014-apps

      - name: build-release-candidate
        run: docker run --rm --privileged=true -v ./:/src/ -t vipoo/yellow-msx-rc2014-tool-chain:0.0.21 make release-build-package

      - name: Archive (msx/bin) directly
        uses: actions/upload-artifact@v4
        with:
          name: msx-bin
          path: |
            msx/bin

      - name: Archive Documents
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: docs
          path: |
            release/docs.zip

      - name: Archive usb-image
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: usbimage
          path: |
            release/usbimage.zip

      - name: Archive msx-rc2014
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: msx-rc2014
          path: |
            release/msx-rc2014.zip

